version: '3.4'

services:
  imagehub.api:
    image: imagehubapi
    container_name: Api
    build:
      context: .
      dockerfile: src\ImageHub.Api\Dockerfile
    depends_on:
      imagehub.database:
        condition: service_healthy
        restart: true
  imagehub.database:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=imagehub-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: src\ImageHub.Api\Dockerfile
